add start time functionality. Closes #4
PennTex/commuter pull request #5
Opened 2016-12-13 19:53 UTC by johnstamatakos

@marioharper Please review.

2016-12-13 20:45 UTC, marioharper commented on cmd/root.go
> +		var commuteTime int64
not needed if we default it to time.Now().Unix() further down

2016-12-13 20:59 UTC, marioharper commented on cmd/root.go
> +	RootCmd.Flags().StringVarP(&start, "start", "s", "", "Starting commute time (1219:1330 or 1219:0130PM = December 19th at 1:30PM)")
Should be a persistent flag so we can pass this value into the `commuter view` command. That way when they use `commuter view` it is relevant to the time they specified

2016-12-13 20:59 UTC, marioharper commented on cmd/root.go
> +		today := true
determining if the date is today should be its own helper method in the Utils package not a flag manipulated by the format date logic.
```go
utils.DateIsToday(start)
```
can be called wherever, in this case on line 127 `if i == 0 && utils.DateIsToday(start) `

2016-12-13 21:00 UTC, marioharper requested changes

2016-12-13 21:00 UTC, marioharper commented on cmd/root.go
> +		if start != "" {
All of this logic within the if statement should be its own _formatDate helper method in this file.

```go
if start != "" {
    commuteTime = _formatDateInput(start)
}
```

2016-12-13 22:57 UTC, johnstamatakos commented on cmd/root.go
> +		var commuteTime int64
👍

2016-12-13 22:57 UTC, johnstamatakos commented on cmd/root.go
> +		if start != "" {
👍

2016-12-13 22:58 UTC, johnstamatakos commented on cmd/root.go
> +	RootCmd.Flags().StringVarP(&start, "start", "s", "", "Starting commute time (1219:1330 or 1219:0130PM = December 19th at 1:30PM)")
👍

2016-12-14 22:38 UTC, johnstamatakos commented on cmd/root.go
> +		today := true
@marioharper instead of this, I'm going to just use:
`if i == 0 && start == "" `
If the start flag is present, use a time for the first output label.  If the start flag is empty, use "Now".

Same logic without dirtying up the utils.

2016-12-14 23:17 UTC, marioharper approved these changes

2016-12-14 23:18 UTC, marioharper commented
sweet, just going to update the README for the new feature and then i'll merge this through

2016-12-14 23:32 UTC, merged